#!/bin/bash


function find_reverse {
  pwd=$1/
  while [ "$pwd" != "//" ]; do
    if [ -f ${pwd}${2} ]; then
      echo $pwd

      return 0
    fi

    pwd=${pwd%/*/}/;
  done
}


pwd=$(pwd -P)
folder=$(find_reverse $pwd '.vagrant')

if [ $folder ]; then
  test $(find "${folder}.vr_config" -cmin +10 2>&1) && rm "${folder}.vr_config"

  if [ ! -f "${folder}.vr_config" ]; then
    pushd $folder > /dev/null && vagrant ssh-config > .vr_config && popd > /dev/null

    while read f; do
      a=$(echo $f | cut -d ' ' -f 1 | cut -d ':' -f 2)

      grep $a /etc/exports > /dev/null

      if [ $? -eq 0 ]; then
        b=$(echo $f | cut -d ' ' -f 3)

        echo "# ${b} ${a}" >> "${folder}.vr_config"
      fi
    done < <(ssh -qtF "${folder}.vr_config" default "mount" | tr -d '\r')
  fi

  if [ -n "$1" ]; then
    s=( $(tail -n1 "${folder}.vr_config") )
    p=${s[1]}${pwd#${s[2]}*}

    cmd="cd ${p} && $@"
  fi

  ssh -qtF "${folder}.vr_config" default ${cmd:-""}
fi
